
project_id = "ihdlldpltlcshmktyidw"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54322
site_url = "https://ihdlldpltlcshmktyidw.supabase.co"
additional_redirect_urls = ["https://ihdlldpltlcshmktyidw.supabase.co"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_refresh_token_reuse_interval = 10
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[db]
port = 54323

[functions.advance-workflow]
verify_jwt = true

[functions.send-workflow-notification]
verify_jwt = true

[functions.generate-workflow]
verify_jwt = true

[functions.send-user-invitation]
verify_jwt = true

[edge_runtime]
enabled = true
inspector_port = 8083
