// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ihdlldpltlcshmktyidw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImloZGxsZHBsdGxjc2hta3R5aWR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1OTg0MzYsImV4cCI6MjA2NDE3NDQzNn0.el7Y5vSnKfKjDVx6qhsQDS1euuA_13PsgNwsPOuD_qs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);